version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  frontend:
    working_directory: ~/app/udagram/udagram-frontend
    executor: node/default
    steps: 
      - checkout:
          path: ~/app
      - node/install:
          install-yarn: true
          node-version: '14.15.0'
      - run: node --version
      - node/install-packages:
          app-dir: ~/app/udagram/udagram-frontend
      - run:
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: ASIA5UOJQJWQCKI6GN5N
          aws-region: us-east-1
          profile-name: default
      - run:
          name: Deploy Frontend
          command: aws s3 cp --recursive  ./www s3://bucket9372/
  server:
    working_directory: ~/app/udagram/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram/udagram-api
      - aws-cli/install
      - eb/setup
      - run:
          name: Deploy Server
          command: npm run deploy
workflows:
  build_and_deploy:
    jobs:
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
      - frontend:
          filters:
            branches:
              only:
                - main
      - server:
          filters:
            branches:
              only:
                - main
